### ISSUE TITLE
we have issues

### ISSUE THREAD

**Issue by mstuart1** [Openscapes/demo#8]
I could really use some help from @jahoey and @arnejacobs to figure this out.

[see here](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=2ahUKEwjLh7bgl9_gAhUHU98KHZKJBiwQwqsBMAJ6BAgAEAo&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DUj1ykZWtPYI&usg=AOvVaw2DsL8o3-dGxP8LIR2nEWKP)

**Comment by jules32** [comment]
so many issues!
